### PR TITLE
Participant device type has been changed from enum[] to string

### PR DESCRIPTION
**Pull request by TamasSzilagyi84**

### CODE REVIEW

**Comment by Jericho** [comment]
My guess is that you are changing this property because you have encountered a device type that ZoomNet doesn't know about which lead to a `There is no value in the ParticipantDevice enum that corresponds to 'blablabla'` exception. Am I right? This happens from time to time because Zoom does not always document all possible values for a given enumerated type. Here's an example of such a situation: https://github.com/Jericho/ZoomNet/issues/354

If that's the case, I would recommend adding this new device type to the `ParticipantDevice` enum rather converting the property to a string. Better yet, raise an issue in the ZoomNet GitHub repo and I'll be more than happy to add this value to the library.

**Review by SyedShahbaz — APPROVED** [review]

**Comment by TamasSzilagyi84** [comment]
> My guess is that you are changing this property because you have encountered a device type that ZoomNet doesn't know about which lead to a `There is no value in the ParticipantDevice enum that corresponds to 'blablabla'` exception. Am I right? This happens from time to time because Zoom does not always document all possible values for a given enumerated type. Here's an example of such a situation: [Jericho#354](https://github.com/Jericho/ZoomNet/issues/354)
> 
> If that's the case, I would recommend adding this new device type to the `ParticipantDevice` enum rather converting the property to a string. Better yet, raise an issue in the ZoomNet GitHub repo and I'll be more than happy to add this value to the library.

@Jericho Thank you for reviewing this PR; your feedback is appreciated. Recently, when clients use a browser, the Zoom API has been returning values such as "Web Browser Chrome 129." We believe that the variety of browser types and versions is too unpredictable to map to an enum, so we have decided to retain this information as a string.

**Comment by Jericho** [comment]
Do you mind raising an issue in my repo and sharing a few of the various values you have seen? It could prompt other developers who have seen this situation share the "non-standard" value they have received from the API.

This could help me improve the list of known device type or, alternatively, it could help me figure out a better way to convert the string into an enum.

**Comment by Jericho** [comment]
Guys, Zoom is investigating this issue. They are trying to figure out why their API is returning undocumented values in the "device"  JSON node but they are asking for additional info to help them investigate. 

Here's what they are asking:

> I will just need the name of the app that made the API call as well as the email associated with that account in order to investigate this further

Any chance you could provide this information along with the ID of a meeting where you observed an attendee with an undocumented device?

**Pull request merged**
