### PR TITLE
Downgrade the JSON package

### PR DESCRIPTION
**Pull request by MaiklSemenov**
The new version of the JSON library is not compatible with projects.

### CODE REVIEW

**Review by TamasSzilagyi84 — COMMENTED** [review]
I think we should also downgrade 
Logging, DependencyInjection etc..

**Comment by MaiklSemenov** [comment]
> I think we should also downgrade Logging, DependencyInjection etc..

I've downgraded the `Microsoft.Extensions.Logging` package which automatically downgrades others.

**Review by TamasSzilagyi84 — APPROVED** [review]
LGTM

**Comment by Jericho** [comment]
Please be aware that System.Text.Json was upgraded to 8.0.5 in the ZoomNet library because 8.0.4 suffers from a vulnerability disclosed [here](https://github.com/dotnet/announcements/issues/329). Having said that, my understanding of the vulnerability is that it is related to a very specific functionality which ZoomNet does not take advantage of which means that ZoomNet is most likely not affected by this security issue in the first place. Therefore I doubt there's an issue for you to downgrade this Json library but I thought it was important to ensure you were aware.

**Pull request merged**
